# Generated by Django 3.0.8 on 2020-10-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmezapp', '0002_medicine_product1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product1',
        ),
    ]
