# Generated by Django 3.0.8 on 2020-11-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmezapp', '0005_auto_20201108_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='', max_length=50)),
                ('mrp_price', models.FloatField()),
                ('price', models.FloatField()),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(default='', upload_to='pics')),
            ],
        ),
    ]
