# Generated by Django 3.0.8 on 2020-11-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmezapp', '0008_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newregis',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='newregis',
            old_name='phone',
            new_name='password2',
        ),
    ]
