# Generated by Django 2.0.13 on 2020-12-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmezapp', '0009_auto_20201124_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.NullBooleanField(default=False),
        ),
    ]
