# Generated by Django 2.0.13 on 2020-12-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmezapp', '0010_auto_20201202_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_name',
        ),
        migrations.AddField(
            model_name='products',
            name='digital',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='mrp_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(),
        ),
    ]
