# Generated by Django 2.0.13 on 2020-12-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmezapp', '0013_auto_20201203_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
